### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by maque4004** [delosh653/ECHO#1]
Hi, there!
I'm not pretty sure about the data format, two questions:
(1) it is said "If you have unevenly sampled data, choose the smallest resolution and leave all missing column samples blank." on the README.md page-- Data Format Example part. My data is uneven sampled, I am wondering if ECHO works for unevenly sampled data?
While I have also read the document of R package "echo.find", it pointed that genes argument in echo_find function must have evenly spaced time points. So I am confused.
(2) My data have no repeated measure, each time point I only have one sample. While I am running through the tutorial, I used expressions example data in 'echo.find' package, I only selected the first replicate sample to run 'echo_find' function, but I got an error:
Error in nls.lm(par = start_param, fn = fcn_single_one_rep, fcall = alt_form,  : 
  evaluation of fn function returns non-sensible value!
Here are my codes:
`expressions.one <- expressions[c(1, seq(2, 73, by = 3))]
echo_find(genes = expressions.one, begin = 2, end = 48, resol = 2, num_reps = 1, low = 20, high = 26, run_all_per = FALSE, paired = FALSE, rem_unexpr = FALSE, is_normal = FALSE, is_de_linear_trend = FALSE, is_smooth = FALSE)`
Do you have any suggestion?
Thank you for your help in advance!

Best,
Jericho

**Comment by delosh653** [comment]
Hi Jericho, thanks for your interest in using ECHO!

1. ECHO works for unevenly sampled data, by choosing the smallest resolution between available points and inserting missing columns for datapoints not reflected. For example, let's say I only had time points 2,3,5,9,10. The smallest resolution between these data points is 1. So my data would look like the following:

| Gene | TP2 | TP3 | TP4 | TP5 | TP6 | TP7 | TP8 | TP9 | TP10 |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| Sample 1 | # | # |  | # |  |  |  | # | # |

where the # are corresponding numbers. I left blank the samples that I didn't have, and my time points that I would enter into the program would be from 2 to 10 with a resolution of 1.

2. I cannot replicate this (ECHO does work with one replicate). When running your code, I get the expected output. I would recommend restarting R and clearing your workspace -- there may be something in there that is hidden and affecting your code.

Hope this helps!

**Comment by delosh653** [comment]
I'm going to close this, since it seems like the problem might be solved. If you have any more questions on this subject, please feel free to open the issue again or use the contact info in the README.
